### ISSUE TITLE
NullPointerException when trying to submit form

### ISSUE THREAD

**Issue by nadavfima** [rm3l/maoni#11]
Had a couple of error reports

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
       at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
       at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
       at org.rm3l.maoni.ui.MaoniActivity.validateAndSubmitForm(MaoniActivity.java:536)
       at org.rm3l.maoni.ui.MaoniActivity.access$100(MaoniActivity.java:70)
       at org.rm3l.maoni.ui.MaoniActivity$2.onClick(MaoniActivity.java:287)
       at android.view.View.performClick(View.java:5637)
       at android.view.View$PerformClick.run(View.java:22433)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by rm3l** [comment]
Just saw this issue. Thanks for reporting, @nadavfima . Looking into it.
